server.port=${PORT:8080}

spring.application.name=moodsync

# Connection String
spring.datasource.url=jdbc:postgresql://gmulkyekanniqwbghitm.supabase.co:5432/postgres

# Credentials
spring.datasource.username=postgres
spring.datasource.password=Coder@20262

# Driver Class
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pooling (Optional but recommended)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
