spring.application.name=moodsync
spring.datasource.url=jdbc:mysql://localhost:3306/moodsync
spring.datasource.username=root
spring.datasource.password=Coder@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
